### ISSUE TITLE
BetterFriendship

### ISSUE THREAD

**Issue by kwiknik78** [stardewrocks/android-compatible-mods#23]
Mod name Better Friendship
UniqueID BetterFriendship
Working Status (old_version)
Working Download link
https://www.nexusmods.com/Core/Libs/Common/Widgets/ModRequirementsPopUp?id=47940&game_id=1303
Latest Download link
https://www.nexusmods.com/Core/Libs/Common/Widgets/ModRequirementsPopUp?id=49454&game_id=1303
Working version 1 0.1
Latest version 1.0.6
Your SMAPI log
https://smapi.io/log/c3cba7daa5b740ee9598afb8a8612c3f

**Comment by Rogue-Toast** [comment]
Added edits to my latest PR.
