### ISSUE TITLE
Better Junimos/Forrestry not working

### ISSUE THREAD

**Issue by mrFoxxibln** [stardewrocks/android-compatible-mods#28]
As the title suggests, Better Junimos doesn't work. Error log says there are files in the mod folder, but no .json. . .
What can I do?

thanks you lovely Farmers

**Comment by AnotherPillow** [comment]
> As the title suggests, Better Junimos doesn't work. Error log says there are files in the mod folder, but no .json. . . What can I do?
> 
> thanks you lovely Farmers

1. This is not the place to get mod support
2. You didn't even read the instructions before asking for support.
